# Generated by Django 3.2.19 on 2024-12-18 20:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0004_auto_20241218_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free_plan', 'Free Plan'), ('basic_plan', 'Basic Plan'), ('standard_plan', 'Standard Plan'), ('premium_plan', 'Premium Plan')], help_text='The name of the subscription plan.', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the plan.', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='The price of the subscription plan.', max_digits=10)),
                ('duration', models.PositiveIntegerField(help_text='Duration of the subscription plan in days.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Start date of the subscription.')),
                ('end_date', models.DateTimeField(blank=True, help_text='End date of the subscription. Calculated based on start date and plan duration.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the subscription is currently active.')),
                ('auto_renew', models.BooleanField(default=False, help_text='Whether the subscription will automatically renew after expiration.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the subscription was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the subscription was last updated.')),
                ('plan', models.ForeignKey(help_text='The subscription plan selected by the tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscription.subscriptionplan')),
                ('tenant', models.OneToOneField(help_text='The tenant this subscription belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
    ]
