# Generated by Django 3.2.19 on 2024-12-19 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_auto_20241219_1347'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(help_text='Start date of the subscription.')),
                ('end_date', models.DateTimeField(blank=True, help_text='End date of the subscription.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the subscription was active at the time of logging.')),
                ('auto_renew', models.BooleanField(default=False, help_text='Whether the subscription was set to auto-renew.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this history entry was created.')),
                ('plan', models.ForeignKey(help_text='The subscription plan for this history entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_history', to='subscription.subscriptionplan')),
                ('tenant', models.ForeignKey(help_text='The tenant this subscription history belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='subscription_history', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Subscription History',
                'verbose_name_plural': 'Subscription Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
