# Generated by Django 3.2.19 on 2024-12-20 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_auto_20241219_1347'),
        ('subscription', '0002_subscriptionhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('paystack', 'Paystack'), ('other', 'Other')], help_text='The payment method name.', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Additional details about the payment option (e.g., account info for bank transfer).', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this payment option is currently available.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Option',
                'verbose_name_plural': 'Payment Options',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount paid.', max_digits=10)),
                ('transaction_reference', models.CharField(blank=True, help_text='The reference number for the transaction.', max_length=255, null=True)),
                ('is_successful', models.BooleanField(default=False, help_text='Whether the payment was successful.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the payment was made.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the payment was last updated.')),
                ('payment_option', models.ForeignKey(help_text='The payment method used for this transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.paymentoption')),
                ('subscription', models.ForeignKey(help_text='The subscription this payment is related to.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscription.subscription')),
                ('tenant', models.ForeignKey(help_text='The tenant making the payment.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
