# Generated by Django 3.2.19 on 2024-12-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_payment_paymentoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_reference',
            field=models.CharField(blank=True, help_text='The reference number for the transaction.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentoption',
            name='description',
            field=models.TextField(blank=True, help_text='Additional details about the payment option.', null=True),
        ),
        migrations.AlterField(
            model_name='paymentoption',
            name='name',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('paystack', 'Paystack'), ('paypal', 'PayPal'), ('flutterwave', 'Flutterwave'), ('stripe', 'Stripe')], help_text='The payment method name.', max_length=50, unique=True),
        ),
    ]
