# Generated by Django 3.2.19 on 2024-12-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_auto_20241223_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Whether the subscription is currently active.'),
        ),
    ]
