# Generated by Django 3.2.19 on 2025-01-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_alter_subscription_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
