# Generated by Django 3.2.19 on 2025-01-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_payment_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
