# Generated by Django 3.2.19 on 2025-01-25 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0010_historicdata_inventoryaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryaudit',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
            preserve_default=False,
        ),
    ]
