# Generated by Django 3.2.19 on 2025-01-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0012_historicdata_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('paystack', 'Paystack'), ('bank', 'Bank Transfer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
            preserve_default=False,
        ),
    ]
