# Generated by Django 3.2.19 on 2025-02-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0013_auto_20250127_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='uncompleted_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('order_id', models.IntegerField()),
                ('ordered_date', models.DateTimeField()),
                ('payment_made', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('complete', models.BooleanField(default=False)),
                ('product', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
