# Generated by Django 3.2.19 on 2025-01-02 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0008_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetUpPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_type', models.CharField(choices=[('font-sans', 'Sans Serif (font-sans)'), ('font-serif', 'Serif (font-serif)'), ('font-mono', 'Monospace (font-mono)')], default='font-sans', max_length=20)),
                ('header_footer_color', models.CharField(choices=[('gray', 'Gray'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('red', 'Red'), ('green', 'Green'), ('purple', 'Purple'), ('pink', 'Pink'), ('indigo', 'Indigo')], default='gray', max_length=20)),
                ('header_footer_color_shade', models.CharField(choices=[('50', '50'), ('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500'), ('600', '600'), ('700', '700'), ('800', '800'), ('900', '900')], default='500', max_length=3)),
                ('logo', models.ImageField(blank=True, help_text='Upload a logo for the page.', null=True, upload_to='logos/')),
                ('background_color', models.CharField(choices=[('gray', 'Gray'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('red', 'Red'), ('green', 'Green'), ('purple', 'Purple'), ('pink', 'Pink'), ('indigo', 'Indigo')], default='gray', max_length=20)),
                ('background_color_shade', models.CharField(choices=[('50', '50'), ('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500'), ('600', '600'), ('700', '700'), ('800', '800'), ('900', '900')], default='100', max_length=3)),
                ('button_color', models.CharField(choices=[('gray', 'Gray'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('red', 'Red'), ('green', 'Green'), ('purple', 'Purple'), ('pink', 'Pink'), ('indigo', 'Indigo')], default='green', max_length=20)),
                ('button_color_shade', models.CharField(choices=[('50', '50'), ('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500'), ('600', '600'), ('700', '700'), ('800', '800'), ('900', '900')], default='500', max_length=3)),
                ('custom_css', models.TextField(blank=True, help_text='Add custom CSS to override default styles.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Page Setup',
                'verbose_name_plural': 'Page Settings',
            },
        ),
    ]
