# Generated by Django 3.2.19 on 2025-01-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setuppage',
            name='banner',
            field=models.ImageField(blank=True, help_text='Upload a banner to display at the top of the page.', null=True, upload_to='banners/'),
        ),
    ]
