# Generated by Django 3.2.19 on 2025-01-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_settings', '0002_setuppage_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_point', models.CharField(default='free delivery', max_length=250)),
                ('delivery_note', models.CharField(blank=True, max_length=250)),
                ('Delivery_amount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='setuppage',
            name='notification_msg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='setuppage',
            name='whatsApp_number',
            field=models.IntegerField(default=123456789),
        ),
    ]
