# Generated by Django 3.2.19 on 2025-01-03 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0008_alter_product_name'),
        ('page_settings', '0003_auto_20250103_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_point', models.CharField(default='free delivery', help_text='Location or method description', max_length=250)),
                ('delivery_note', models.CharField(blank=True, help_text='Additional notes about the delivery', max_length=250)),
                ('delivery_amount', models.DecimalField(decimal_places=2, help_text='Delivery cost', max_digits=10)),
                ('delivery_type', models.CharField(choices=[('standard', 'Standard Delivery'), ('express', 'Express Delivery'), ('same_day', 'Same Day Delivery'), ('pickup', 'Pickup')], default='standard', help_text='Type of delivery service', max_length=20)),
                ('estimated_delivery_time', models.CharField(blank=True, help_text='Estimated delivery time (e.g., 3-5 business days)', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this delivery method')),
                ('region_served', models.CharField(blank=True, help_text='Region or area served by this delivery method', max_length=250)),
                ('max_weight_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum weight limit for the delivery (in kg)', max_digits=10, null=True)),
                ('max_package_dimensions', models.CharField(blank=True, help_text='Maximum dimensions allowed for a package (e.g., LxWxH in cm)', max_length=100)),
                ('cutoff_time', models.TimeField(blank=True, help_text='Order cutoff time for same-day or next-day delivery', null=True)),
                ('available_days', models.CharField(blank=True, help_text='Days when delivery is available (e.g., Mon-Fri)', max_length=250)),
                ('supports_tracking', models.BooleanField(default=False, help_text='Indicates if this method supports tracking')),
                ('handling_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional handling fee (if any)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Delivery Method',
                'verbose_name_plural': 'Delivery Methods',
            },
        ),
        migrations.DeleteModel(
            name='Delivery_method',
        ),
    ]
