# Generated by Django 3.2.19 on 2025-02-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_settings', '0004_auto_20250103_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='setuppage',
            name='text_color',
            field=models.CharField(choices=[('gray', 'Gray'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('red', 'Red'), ('green', 'Green'), ('purple', 'Purple'), ('pink', 'Pink'), ('indigo', 'Indigo')], default='gray', max_length=20),
        ),
        migrations.AddField(
            model_name='setuppage',
            name='text_color_shade',
            field=models.CharField(choices=[('50', '50'), ('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500'), ('600', '600'), ('700', '700'), ('800', '800'), ('900', '900')], default='100', max_length=3),
        ),
    ]
