# Generated by Django 3.2.19 on 2025-02-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_and_features', '0002_storevisit_userevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userevent',
            old_name='timestamp',
            new_name='click_time',
        ),
        migrations.AddField(
            model_name='userevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userevent',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userevent',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='event_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
