# Generated by Django 3.2.19 on 2025-02-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_and_features', '0003_auto_20250220_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userevent',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userevent',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userevent',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userevent',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userevent',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
