# Generated by Django 3.2.19 on 2025-02-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_and_features', '0004_auto_20250220_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='latitude',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='longitude',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
