# Generated by Django 3.2.19 on 2025-02-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_and_features', '0005_auto_20250220_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='asn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userevent',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userevent',
            name='isp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userevent',
            name='org',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userevent',
            name='region_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userevent',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userevent',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='event_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
